### Health Check
GET http://127.0.0.1:8000/health_check

### Subscribe
POST https://zero2prod-jf74b.ondigitalocean.app/subscriptions
Content-Type: application/x-www-form-urlencoded

name=odd
&email=odd@testss.com
